- name: Install Apache web server
  ansible.builtin.package:
    name: apache2
    state: present

- name: Ensure Apache is started and enabled
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes

- name: Open port 80 in firewall
  ansible.builtin.ufw:
    port: '80'
    state: enabled
    proto: tcp

- name: Create custom index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: restart apache

- name: Wait for Apache to start
  ansible.builtin.wait_for:
    port: 80
    delay: 5
    timeout: 30

- name: Check website availability
  ansible.builtin.uri:
    url: "http://localhost"
    status_code: 200
    timeout: 10
