- name: download apache
  hosts: all
  become: yes
  vars:
    kafka_version: "3.6.1"
    kafka_skala_version: "2.13"
    install_dir: "/home/herusl/kafka"
  tasks:
    - name: create dir
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'
    - name: download apache
      get_url:
        url:"https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
        dest: "/tmp/kafka.tgz"
        checksum: "sha512:https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz.sha512"
        timeout: 60

    - name: Extract Kafka archive
      unarchive:
        src: "/tmp/kafka.tgz"
        dest: "{{ install_dir }}"
        remote_src: yes
        extra_opts: ["--strip-components=1"]
        
