- name: Install and configure tuned
  hosts: all
  become: yes

  tasks:
    - name: Install tuned package
      package:
        name: tuned
        state: present

    - name: Start tuned service
      systemd:
        name: tuned
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Enable and start tuned profile
      command: tuned-adm profile throughput-performance
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Ensure tuned is running
      service:
        name: tuned
        state: started
        enabled: yes
